# Generated by Django 5.1.6 on 2025-03-25 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('cant_cajas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('cant_piezas', models.IntegerField()),
                ('id_parle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parle')),
            ],
        ),
        migrations.CreateModel(
            name='pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caja')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(max_length=200)),
                ('id_caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caja')),
            ],
        ),
    ]
