# Generated by Django 5.1.6 on 2025-03-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='id_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='core.caja'),
        ),
    ]
