# Generated by Django 5.1.6 on 2025-03-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pieza_id_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
