# Generated by Django 5.1.6 on 2025-03-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pieza_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='codigo',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Código único'),
        ),
    ]
