# Generated by Django 5.1.6 on 2025-04-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pieza_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_de_pieza',
            name='id_caja',
        ),
        migrations.RemoveField(
            model_name='tipo_de_pieza',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='pieza',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipo_de_pieza'),
        ),
        migrations.AlterField(
            model_name='tipo_de_pieza',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
