# Generated by Django 5.1.6 on 2025-04-03 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tipo_de_pieza_id_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_de_pieza',
            name='id_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caja'),
        ),
        migrations.AddField(
            model_name='tipo_de_pieza',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_de_pieza',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
