# Generated by Django 5.1.6 on 2025-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tipo_de_pieza_id_caja_tipo_de_pieza_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parle',
            name='alto',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='parle',
            name='ancho',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='parle',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parle',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parle',
            name='cant_cajas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parle',
            name='nombre',
            field=models.CharField(blank=True, default='Nuevo Parle', max_length=200, null=True),
        ),
    ]
