# Generated by Django 5.1.6 on 2025-04-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parle_alto_parle_ancho_parle_pos_x_parle_pos_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='id_parle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parle', verbose_name='Parle asociado'),
        ),
    ]
